const NAME_REGEX = /^[a-zA-Zа-яёА-ЯЁ -]+$/u;
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const MAX_SCREEN_WIDTH = 1280;
const MID_SCREEN_WIDTH = 768;

const MAX_MOVIES_PER_PAGE = 12;
const MID_MOVIES_PER_PAGE = 8;
const MIN_MOVIES_PER_PAGE = 5;

const MAX_ADDITION = 3;
const MIN_ADDITION = 2;

const SHORT_MOVIE_LENGTH = 40;

export { NAME_REGEX, EMAIL_REGEX, MAX_SCREEN_WIDTH, MID_SCREEN_WIDTH, MAX_MOVIES_PER_PAGE, MID_MOVIES_PER_PAGE, MIN_MOVIES_PER_PAGE, MAX_ADDITION, MIN_ADDITION, SHORT_MOVIE_LENGTH }